# ChEMBL
- 화합물 데이터베이스 중 하나입니다. 특정 화합물이나 증상같은걸로 검색하면 관련된 화합물을 찾아주는 서비스입니다.
- 검색 결과를 csv 파일로 저장할 수 있습니다.
- 뭐 가져오는 라이브러리도 있는 것 같은데 오늘은 예전에 받아뒀던거 걍 쓸겁니다. 

## 프로젝트 정보
- 인원: 1인
- 파이썬 버전: 3.10
- 데이터 리소스: ChEMBL
- 필요한 모듈: Numpy, Pandas, Matplotlib, Seaborn

In [1]:
# 모! 듈! 
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from chembl_webresource_client.new_client import new_client # 켐블털이 

# 그래프 기본 테마 설정
sns.set_theme(palette="viridis", style="whitegrid", font_scale=1) # 블루톤

# 그래프를 그리기 위한 기본 설정
plt.rcParams['font.family'] = 'Galmuri11' # 제가... 픽셀체 이런거 좋아해서... 
# plt.rcParams['font.family'] = 'AppleGothic'
plt.rcParams['figure.figsize'] = 12, 6
plt.rcParams['font.size'] = 14 # 기본 폰트사이즈 (자세한 양식은 하기)
plt.rcParams['axes.unicode_minus'] = False

/opt/anaconda3/envs/tensorflow_base/lib/python3.10/site-packages/chembl_webresource_client/__init__.py:4: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  __version__ = __import__('pkg_resources').get_distribution('chembl_webresource_client').version

In [2]:
data_df = pd.read_csv("data/Ibuprofen.csv", sep=";") # 구분자가 ;
data_df

,ChEMBL ID,Name,Synonyms,Type,Max Phase,Molecular Weight,Targets,Bioactivities,AlogP,Polar Surface Area,...,Heavy Atoms,Np Likeness Score,Molecular Formula,Smiles,Inchi Key,Inchi,Withdrawn Flag,Orphan,Records Key,Records Name
0,CHEMBL253765,(R)-SUPROFEN,NaN,Small molecule,NaN,260.31,12.0,15.0,3.17,54.37,...,18,-0.81,C14H12O3S,C[C@@H](C(=O)O)c1ccc(C(=O)c2cccs2)cc1,MDKGKXOCJGEUJW-SECBINFHSA-N,InChI=1S/C14H12O3S/c1-9(14(16)17)10-4-6-11(7-5...,False,-1,"['SID11112759', '212, suprofen (R)', 'Suprofen...","['SID11112759', '(R)-2-(4-(thiophene-5-carbony..."
1,CHEMBL2104170,CLIPROFEN,"CLIPROFEN|CLIPROFENE|CLIPROFENO|R-25,160|R-25160",Small molecule,2.0,294.76,NaN,NaN,3.82,54.37,...,19,-1.23,C14H11ClO3S,CC(C(=O)O)c1ccc(C(=O)c2cccs2)c(Cl)c1,NLGUJWNOGYWZBI-UHFFFAOYSA-N,InChI=1S/C14H11ClO3S/c1-8(14(17)18)9-4-5-10(11...,False,0,"['CLIPROFEN', 'CLIPROFEN']","['CLIPROFEN', 'CLIPROFEN']"
2,CHEMBL2107442,LOBUPROFEN,LOBUPROFEN|LOBUPROFENE|LOBUPROFENO,Small molecule,2.0,429.00,NaN,NaN,5.01,32.78,...,30,-1.12,C25H33ClN2O2,CC(C)Cc1ccc(C(C)C(=O)OCCN2CCN(c3cccc(Cl)c3)CC2...,JFGXBHHLHQAGRR-UHFFFAOYSA-N,InChI=1S/C25H33ClN2O2/c1-19(2)17-21-7-9-22(10-...,False,0,['LOBUPROFEN'],['LOBUPROFEN']
3,CHEMBL4297164,XIMOPROFEN,XIMOPROFEN|XIMOPROFENE|XIMOPROFENO,Small molecule,2.0,261.32,1.0,1.0,3.36,69.89,...,19,0.16,C15H19NO3,CC(C(=O)O)c1ccc(C2CCCC(=NO)C2)cc1,IQPPOXSMSDPZKU-UHFFFAOYSA-N,InChI=1S/C15H19NO3/c1-10(15(17)18)11-5-7-12(8-...,False,0,"['Ximoprofen', 'XIMOPROFEN']","['Ximoprofen', 'XIMOPROFEN']"
4,CHEMBL2107432,LOSMIPROFEN,LOSMIPROFEN|LOSMIPROFENE|LOSMIPROFENO,Small molecule,2.0,318.76,NaN,NaN,3.73,63.60,...,22,-0.76,C17H15ClO4,Cc1c(OC(C)C(=O)O)cccc1C(=O)c1ccc(Cl)cc1,JQYJAGNNCNBFRM-UHFFFAOYSA-N,InChI=1S/C17H15ClO4/c1-10-14(16(19)12-6-8-13(1...,False,0,['LOSMIPROFEN'],['LOSMIPROFEN']
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,CHEMBL341922,KETOPROFEN SODIUM,DIRACTIN|KETOPROFEN SODIUM|SODIUM KETOPROFEN,Small molecule,2.0,276.27,2.0,7.0,3.11,54.37,...,19,-0.08,C16H13NaO3,CC(C(=O)[O-])c1cccc(C(=O)c2ccccc2)c1.[Na+],OAPDLBHLMVYMCW-UHFFFAOYSA-M,InChI=1S/C16H14O3.Na/c1-11(16(18)19)13-8-5-9-1...,False,0,"['32', 'KETOPROFEN SODIUM']",['Sodium salt 2-(3-benzoyl-phenyl)-propionate'...
59,CHEMBL2106966,PIKETOPROFEN,CALMATEL|PIKETOPROFEN|PIKETOPROFENE|PIKETOPROFENO,Small molecule,2.0,344.41,3.0,7.0,4.36,59.06,...,26,-1.02,C22H20N2O2,Cc1ccnc(NC(=O)C(C)c2cccc(C(=O)c3ccccc3)c2)c1,ASFKKFRSMGBFRO-UHFFFAOYSA-N,InChI=1S/C22H20N2O2/c1-15-11-12-23-20(13-15)24...,False,0,"['PIKETOPROFEN', 'PIKETOPROFEN', 'piketoprofen...","['PIKETOPROFEN', 'PIKETOPROFEN', 'piketoprofen..."
60,CHEMBL1297,FENOPROFEN,53858|FENOPROFEN|FENOPROFENE|FENOPROFENO|LILLY...,Small molecule,4.0,242.27,145.0,719.0,3.67,46.53,...,18,-0.26,C15H14O3,CC(C(=O)O)c1cccc(Oc2ccccc2)c1,RDJGLLICXDHJDY-UHFFFAOYSA-N,InChI=1S/C15H14O3/c1-11(15(16)17)12-6-5-9-14(1...,False,0,"['780', 'fenoprofen', '(R,S)-Fenoprofen', 'Fen...","[None, 'fenoprofen', 'Fenoprofen', 'Fenoprofen..."
61,CHEMBL188952,PIRPROFEN,PIRPROFEN|PIRPROFENE|PIRPROFENO|RACEMIC PIRPRO...,Small molecule,4.0,251.71,92.0,163.0,2.90,40.54,...,17,-0.53,C13H14ClNO2,CC(C(=O)O)c1ccc(N2CC=CC2)c(Cl)c1,PIDSZXPFGCURGN-UHFFFAOYSA-N,InChI=1S/C13H14ClNO2/c1-9(13(16)17)10-4-5-12(1...,True,0,"['Pirprofen', 'Pirprofen (table 1)', 'PIRPROFE...","['Pirprofen', '2-[3-Chloro-4-(2,5-dihydro-pyrr..."
62,CHEMBL15870,INDOPROFEN,BOR-IND|FLOSIN|FLOSINT|INDOPROFEN|INDOPROFENE|...,Small molecule,4.0,281.31,97.0,154.0,3.04,57.61,...,21,-0.39,C17H15NO3,CC(C(=O)O)c1ccc(N2Cc3ccccc3C2=O)cc1,RJMIEHBSYVWVIN-UHFFFAOYSA-N,InChI=1S/C17H15NO3/c1-11(17(20)21)12-6-8-14(9-...,True,0,"['indoprofen', 'INDOPROFEN', 'INDOPROFEN', '9'...","['2-[4-(1-Oxo-1,3-dihydro-isoindol-2-yl)-pheny..."

# 데이터 정보 확인

## df.shape

In [3]:
data_df.shape

(63, 29)

## df.info()

In [4]:
data_df.info() # 얼마 되지도 않는거에 널까지 껴있네

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63 entries, 0 to 62
Data columns (total 29 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ChEMBL ID           63 non-null     object
 1   Name                62 non-null     object
 2   Synonyms            59 non-null     object
 3   Type                63 non-null     object
 4   Max Phase           59 non-null     float64
 5   Molecular Weight    63 non-null     float64
 6   Targets             40 non-null     float64
 7   Bioactivities       40 non-null     float64
 8   AlogP               63 non-null     float64
 9   Polar Surface Area  63 non-null     float64
 10  HBA                 63 non-null     int64
 11  HBD                 63 non-null     int64
 12  #RO5 Violations     63 non-null     int64
 13  #Rotatable Bonds    63 non-null     int64
 14  Passes Ro3          63 non-null     object
 15  QED Weighted        63 non-null     float64
 16  Aromatic Rings      63 non-null     int64
 17  Structure Type      63 non-null     object
 18  Inorganic Flag      63 non-null     int64
 19  Heavy Atoms         63 non-null     int64
 20  Np Likeness Score   63 non-null     float64
 21  Molecular Formula   63 non-null     object
 22  Smiles              63 non-null     object
 23  Inchi Key           63 non-null     object
 24  Inchi               63 non-null     object
 25  Withdrawn Flag      63 non-null     bool
 26  Orphan              63 non-null     int64
 27  Records Key         63 non-null     object
 28  Records Name        63 non-null     object
dtypes: bool(1), float64(8), int64(8), object(12)
memory usage: 14.0+ KB

## df.describe()

In [5]:
data_df.describe()
# 여기 나왔어도 범주형인것도 있습니다.

,Max Phase,Molecular Weight,Targets,Bioactivities,AlogP,Polar Surface Area,HBA,HBD,#RO5 Violations,#Rotatable Bonds,QED Weighted,Aromatic Rings,Inorganic Flag,Heavy Atoms,Np Likeness Score,Orphan
count,59.000000,63.000000,40.000000,40.00000,63.000000,63.000000,63.000000,63.000000,63.000000,63.000000,63.000000,63.000000,63.000000,63.000000,63.000000,63.000000
mean,2.474576,286.804603,61.400000,282.35000,3.535079,48.665238,2.317460,0.968254,0.063492,3.984127,0.803175,1.841270,-0.063492,19.571429,-0.363492,-0.063492
std,1.164947,64.184537,87.147914,691.58282,0.694833,11.659890,1.044577,0.567060,0.245805,1.539712,0.097299,0.676956,0.245805,3.509040,0.536603,0.245805
min,-1.000000,206.280000,1.000000,1.00000,2.100000,29.540000,1.000000,0.000000,0.000000,2.000000,0.490000,1.000000,-1.000000,15.000000,-1.510000,-1.000000
25%,2.000000,248.805000,2.000000,5.75000,3.070000,37.300000,1.000000,1.000000,0.000000,3.000000,0.755000,1.000000,0.000000,18.000000,-0.785000,0.000000
50%,2.000000,266.300000,8.500000,16.00000,3.430000,49.850000,2.000000,1.000000,0.000000,4.000000,0.820000,2.000000,0.000000,19.000000,-0.420000,0.000000
75%,4.000000,300.045000,102.750000,239.75000,3.825000,54.485000,3.000000,1.000000,0.000000,4.000000,0.865000,2.000000,0.000000,21.000000,0.070000,0.000000
max,4.000000,558.640000,375.000000,4089.00000,5.880000,86.630000,5.000000,3.000000,1.000000,9.000000,0.940000,3.000000,0.000000,33.000000,0.920000,0.000000

In [6]:
data_df.describe(include="O")

,ChEMBL ID,Name,Synonyms,Type,Passes Ro3,Structure Type,Molecular Formula,Smiles,Inchi Key,Inchi,Records Key,Records Name
count,63,62,59,63,63,63,63,63,63,63,63,63
unique,63,62,59,1,2,1,53,63,63,63,63,63
top,CHEMBL253765,(R)-SUPROFEN,"CLIPROFEN|CLIPROFENE|CLIPROFENO|R-25,160|R-25160",Small molecule,N,MOL,C14H12O3S,C[C@@H](C(=O)O)c1ccc(C(=O)c2cccs2)cc1,MDKGKXOCJGEUJW-SECBINFHSA-N,InChI=1S/C14H12O3S/c1-9(14(16)17)10-4-6-11(7-5...,"['SID11112759', '212, suprofen (R)', 'Suprofen...","['SID11112759', '(R)-2-(4-(thiophene-5-carbony..."
freq,1,1,1,63,61,63,3,1,1,1,1,1

## df.isna().sum()

In [7]:
data_df.isna().sum() 
# 아 널이예요... 
# 근데 이 널은 우리가 몰라서 못 채워요...

ChEMBL ID              0
Name                   1
Synonyms               4
Type                   0
Max Phase              4
Molecular Weight       0
Targets               23
Bioactivities         23
AlogP                  0
Polar Surface Area     0
HBA                    0
HBD                    0
#RO5 Violations        0
#Rotatable Bonds       0
Passes Ro3             0
QED Weighted           0
Aromatic Rings         0
Structure Type         0
Inorganic Flag         0
Heavy Atoms            0
Np Likeness Score      0
Molecular Formula      0
Smiles                 0
Inchi Key              0
Inchi                  0
Withdrawn Flag         0
Orphan                 0
Records Key            0
Records Name           0
dtype: int64

## df.head()

In [8]:
data_df.head()

,ChEMBL ID,Name,Synonyms,Type,Max Phase,Molecular Weight,Targets,Bioactivities,AlogP,Polar Surface Area,...,Heavy Atoms,Np Likeness Score,Molecular Formula,Smiles,Inchi Key,Inchi,Withdrawn Flag,Orphan,Records Key,Records Name
0,CHEMBL253765,(R)-SUPROFEN,NaN,Small molecule,NaN,260.31,12.0,15.0,3.17,54.37,...,18,-0.81,C14H12O3S,C[C@@H](C(=O)O)c1ccc(C(=O)c2cccs2)cc1,MDKGKXOCJGEUJW-SECBINFHSA-N,InChI=1S/C14H12O3S/c1-9(14(16)17)10-4-6-11(7-5...,False,-1,"['SID11112759', '212, suprofen (R)', 'Suprofen...","['SID11112759', '(R)-2-(4-(thiophene-5-carbony..."
1,CHEMBL2104170,CLIPROFEN,"CLIPROFEN|CLIPROFENE|CLIPROFENO|R-25,160|R-25160",Small molecule,2.0,294.76,NaN,NaN,3.82,54.37,...,19,-1.23,C14H11ClO3S,CC(C(=O)O)c1ccc(C(=O)c2cccs2)c(Cl)c1,NLGUJWNOGYWZBI-UHFFFAOYSA-N,InChI=1S/C14H11ClO3S/c1-8(14(17)18)9-4-5-10(11...,False,0,"['CLIPROFEN', 'CLIPROFEN']","['CLIPROFEN', 'CLIPROFEN']"
2,CHEMBL2107442,LOBUPROFEN,LOBUPROFEN|LOBUPROFENE|LOBUPROFENO,Small molecule,2.0,429.00,NaN,NaN,5.01,32.78,...,30,-1.12,C25H33ClN2O2,CC(C)Cc1ccc(C(C)C(=O)OCCN2CCN(c3cccc(Cl)c3)CC2...,JFGXBHHLHQAGRR-UHFFFAOYSA-N,InChI=1S/C25H33ClN2O2/c1-19(2)17-21-7-9-22(10-...,False,0,['LOBUPROFEN'],['LOBUPROFEN']
3,CHEMBL4297164,XIMOPROFEN,XIMOPROFEN|XIMOPROFENE|XIMOPROFENO,Small molecule,2.0,261.32,1.0,1.0,3.36,69.89,...,19,0.16,C15H19NO3,CC(C(=O)O)c1ccc(C2CCCC(=NO)C2)cc1,IQPPOXSMSDPZKU-UHFFFAOYSA-N,InChI=1S/C15H19NO3/c1-10(15(17)18)11-5-7-12(8-...,False,0,"['Ximoprofen', 'XIMOPROFEN']","['Ximoprofen', 'XIMOPROFEN']"
4,CHEMBL2107432,LOSMIPROFEN,LOSMIPROFEN|LOSMIPROFENE|LOSMIPROFENO,Small molecule,2.0,318.76,NaN,NaN,3.73,63.60,...,22,-0.76,C17H15ClO4,Cc1c(OC(C)C(=O)O)cccc1C(=O)c1ccc(Cl)cc1,JQYJAGNNCNBFRM-UHFFFAOYSA-N,InChI=1S/C17H15ClO4/c1-10-14(16(19)12-6-8-13(1...,False,0,['LOSMIPROFEN'],['LOSMIPROFEN']

## df.columns

In [9]:
data_df.columns

Index(['ChEMBL ID', 'Name', 'Synonyms', 'Type', 'Max Phase',
       'Molecular Weight', 'Targets', 'Bioactivities', 'AlogP',
       'Polar Surface Area', 'HBA', 'HBD', '#RO5 Violations',
       '#Rotatable Bonds', 'Passes Ro3', 'QED Weighted', 'Aromatic Rings',
       'Structure Type', 'Inorganic Flag', 'Heavy Atoms', 'Np Likeness Score',
       'Molecular Formula', 'Smiles', 'Inchi Key', 'Inchi', 'Withdrawn Flag',
       'Orphan', 'Records Key', 'Records Name'],
      dtype='object')

# 전처리

## 분자량 범주화
- 500보다 큰가, 작은가로 나눌거다. 
- 왜냐고요? RO5(리핀스키의 Rule of 5)에 따라 500보다 큰 분자는 거의 약이 아니기 때문임.

In [10]:
# 분자량이 500보다 크면 헤비 아니면 라이트
data_df['Moecular_classification'] = data_df['Molecular Weight'].apply(lambda x: 'Heavy' if x > 500 else 'Light')

## Max Phase 범주화
- 4 아니면 다 임상중인겁니다. -1은... 어... 힘내라...

In [11]:
# 4: Approved/3~0: Clinical/-1: Failed
data_df['Status'] = data_df['Max Phase'].map({4: 'Approved', 3: 'Clinical', 2: 'Clinical', 1: 'Clinical', 0: 'Clinical', -1: 'Failed'}) 
# 아니 맵합수가 왜 여기서

In [13]:
data_df['Status'].value_counts()

Status
Clinical    40
Approved    17
Failed       2
Name: count, dtype: int64

# 본게임은 지금부터다